/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:9b45427bc8aea9fd28f68a3c814df9e397c124ca 

#pragma once

#include "ex_import_blockMirrorBase.h"


template<typename Ttn = int, bool Tb = false, int Tint = 1>
class ex_import_blockMirror : public ex_import_blockMirrorBase<Ttn, Tb, Tint> {
  public:
    SC_HAS_PROCESS(ex_import_blockMirror);

    ex_import_blockMirror(sc_core::sc_module_name name) : ex_import_blockMirrorBase<Ttn, Tb, Tint>(name) {
    }
};

