/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:4a8c7258c91627c87c734fad95479f19e1f7deb7 


#pragma once

#include <systemc>
#include <scmlinc/scml_property.h>
#include <string>
#include <tlm.h>
#include <scml2.h>
#include <scml.h>



template<typename Ttn = int, bool Tb = false, int Tint = 1>
class ex_import_blockMirrorBase : public sc_core::sc_module {
  public:
    SC_HAS_PROCESS(ex_import_blockMirrorBase);

	typedef ex_import_blockMirrorBase ModelBaseType;

    ex_import_blockMirrorBase(sc_core::sc_module_name name) 
        : sc_core::sc_module(name)
        , p_uint("p_uint", 2)
        , p_bool("p_bool", true)
        , p_double("p_double", 3.14)
        , p_string("p_string", "one")
        , in("in")
        , socket("socket")
        , p_reset("p_reset")
        , p_clk_driver("p_clk_driver")
        , p_clk("p_clk") {
      p_clk(p_clk_driver);
    }
    
    ~ex_import_blockMirrorBase() {
      
    }
    
    /**
     * This method resets all interfaces, registers, and bitfields to their reset value.
     * It is typically called from end_of_elaboration(), and connected to the reset port.
     */
    
    virtual void reset_model() {
    }
    
    virtual void end_of_elaboration() {
      sc_core::sc_module::end_of_elaboration();
      reset_model();
    }
    
    ModelBaseType& model() {
      return *this;
    }
     
    
    
    scml_property<unsigned int> p_uint;
    scml_property<bool> p_bool;
    scml_property<double> p_double;
    scml_property<std::string> p_string;
    
    sc_core::sc_out< bool > in;
    scml2::initiator_socket<32> socket;
    sc_core::sc_out< bool > p_reset;
    scml_clock p_clk_driver;
    sc_core::sc_export<sc_core::sc_signal_inout_if<bool> > p_clk;
    
    
    
    
};

