/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Author:  Synopsy
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:3fa39166843755ae25c7d93442a640bc2c363383 

#pragma once

#include <scml2_testing.h>
#include <SPICtrl.h>
#include <SPICtrlMirror.h>
#include <SPICtrlCovermodel.h>
#include "scml2_protocol_engines/tlm2_ft_initiator_port/include/testing/tlm2_ft_initiator_port_peProxyBase.h"
#include "tlm_ft_spi_proxy.h"
#include "scml2_protocol_engines/reset/include/reset_engine_proxies.h"
#include "scml2_protocol_engines/clock/include/clock_engine_proxies.h"
#include "scml2_protocol_engines/interrupt/include/interrupt_engine_proxies.h"



#include <scml2_testing/fb_test_utils.h>



SCML2_FASTBUILD_COVERAGE(::SPICtrl, "SPICtrl0", "SPICtrl" + std::string(::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") ? std::string(",")+::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") : "") + ",../../SystemC/libso-gcc-12.3-64/FastBuild,..;");



class SPICtrlTestHarness : public scml2::testing::test_group<::SPICtrl, SPICtrlMirror, scml2::testing::fast_build_covergroup<SPICtrlCovermodel > > {
  protected:
    SPICtrlTestHarness() 
        : scml2::testing::test_group<::SPICtrl, SPICtrlMirror, scml2::testing::fast_build_covergroup<SPICtrlCovermodel > >()
        , enable_check_clocks("enable_check_clocks", this->get_property_server())
        , target_id("target_id", this->get_property_server())
        , fifo_size("fifo_size", this->get_property_server())
        , version("version", this->get_property_server())
        , bus_reg_in("bus_reg_in")
        , Serial_IO("Serial_IO")
        , rst_in()
        , spi_clk()
        , clk_in()
        , tfuf_irq("tfuf_irq")
        , tfff_irq("tfff_irq")
        , rfof_irq("rfof_irq")
        , rfdf_irq("rfdf_irq") {
      
    }
    
    scml2::testing::property_proxy<bool> enable_check_clocks;
    scml2::testing::property_proxy<unsigned int> target_id;
    scml2::testing::property_proxy<unsigned int> fifo_size;
    scml2::testing::property_proxy<int> version;
    scml2::tlm2_ft_initiator_port_peProxy<32> bus_reg_in;
    scml2::testing::tlm_ft_spi_proxy Serial_IO;
    sc_core::sc_signal< bool > rst_in_signal;
    scml2::testing::reset_master_engine_proxy rst_in;
    scml2::testing::clock_master_engine_proxy spi_clk;
    scml2::testing::clock_master_engine_proxy clk_in;
    sc_core::sc_signal< bool > tfuf_irq_signal;
    scml2::testing::interrupt_slave_engine_proxy tfuf_irq;
    sc_core::sc_signal< bool > tfff_irq_signal;
    scml2::testing::interrupt_slave_engine_proxy tfff_irq;
    sc_core::sc_signal< bool > rfof_irq_signal;
    scml2::testing::interrupt_slave_engine_proxy rfof_irq;
    sc_core::sc_signal< bool > rfdf_irq_signal;
    scml2::testing::interrupt_slave_engine_proxy rfdf_irq;


#ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    /* coverity[member_decl] */
    int MCR;
    enum {
      MCR_MSTR_input_mode = 0,
      MCR_MSTR_driver_mode = 1,
    };
    enum {
      MCR_PCSSE_chip_select_mode = 0,
      MCR_PCSSE_strobe_mode = 1,
    };
    /* coverity[member_decl] */
    int CTAR;
    /* coverity[member_decl] */
    int SR;
    /* coverity[member_decl] */
    int RSER;
    /* coverity[member_decl] */
    int PUSHR;
    /* coverity[member_decl] */
    int POPR;
    virtual void do_initialize_constants() {
      MCR = 0x0 + 0x0;
      CTAR = 0x0 + 0x4;
      SR = 0x0 + 0x14;
      RSER = 0x0 + 0x18;
      PUSHR = 0x0 + 0x1c;
      POPR = 0x0 + 0x20;
    }

#endif

  protected: 
    virtual void do_initialize_test_group() {
      bus_reg_in.set_target(&this->mirrorModel->bus_reg_in_mockup);
      this->mirrorModel->bus_reg_in(this->modelUnderTest->bus_reg_in);
      Serial_IO.set_target(&this->mirrorModel->Serial_IO_mockup);
      this->mirrorModel->Serial_IO_mockup.doBind(this->modelUnderTest->Serial_IO);
      rst_in.set_target(&this->mirrorModel->rst_in_mockup);
      this->modelUnderTest->rst_in(rst_in_signal);
      this->mirrorModel->rst_in(rst_in_signal);
      spi_clk.set_target(&this->mirrorModel->spi_clk_mockup);
      this->modelUnderTest->spi_clk(this->mirrorModel->spi_clk);
      clk_in.set_target(&this->mirrorModel->clk_in_mockup);
      this->modelUnderTest->clk_in(this->mirrorModel->clk_in);
      tfuf_irq.set_target(&this->mirrorModel->tfuf_irq_mockup);
      this->modelUnderTest->tfuf_irq(tfuf_irq_signal);
      this->mirrorModel->tfuf_irq(tfuf_irq_signal);
      tfff_irq.set_target(&this->mirrorModel->tfff_irq_mockup);
      this->modelUnderTest->tfff_irq(tfff_irq_signal);
      this->mirrorModel->tfff_irq(tfff_irq_signal);
      rfof_irq.set_target(&this->mirrorModel->rfof_irq_mockup);
      this->modelUnderTest->rfof_irq(rfof_irq_signal);
      this->mirrorModel->rfof_irq(rfof_irq_signal);
      rfdf_irq.set_target(&this->mirrorModel->rfdf_irq_mockup);
      this->modelUnderTest->rfdf_irq(rfdf_irq_signal);
      this->mirrorModel->rfdf_irq(rfdf_irq_signal);
    }
    
    virtual void do_initialize_properties() {
      this->init_param(enable_check_clocks, false);
      this->init_param(target_id, 0);
      this->init_param(fifo_size, 5);
      this->init_param(version, 10003);
    }

};


