#############################################################################
# Copyright 1996-2025 Synopsys, Inc.                                        #
#                                                                           #
# This Synopsys software and all associated documentation are proprietary   #
# to Synopsys, Inc. and may only be used pursuant to the terms and          #
# conditions of a written license agreement with Synopsys, Inc.             #
# All other use, reproduction, modification, or distribution of the         #
# Synopsys software or the associated documentation is strictly prohibited. #
#############################################################################
#
# Build script for model 'SPICtrl' generated by TLM Creator 
# 
# Configuration name    : FastBuild
# Configuration options : dynamic_load_library rebuilds_disabled
# 
# Generated at          : 2026/01/11 18:12:30
#
# CHECKSUM:c8586a0b985c7da194f93ebced8c1cc472195593
#
#############################################################################

new_project

source [file normalize [file dirname [info script]]]/SPICtrl_import.tcl

if { ![info exists ::env(TLMCREATOR_CLEAN)]} {
	proc number_of_processors {} {
	if {[info exists ::env(NUMBER_OF_PROCESSORS_OVERRIDE)]} {
		return $::env(NUMBER_OF_PROCESSORS_OVERRIDE)
	}
	switch ${::tcl_platform(platform)} {
		"windows" { 
			if {[info exists ::env(NUMBER_OF_PROCESSORS)]} {
				return $::env(NUMBER_OF_PROCESSORS) 
			} else {
				puts "Warning: failed to access ::env(NUMBER_OF_PROCESSORS)"
				return 1
			}
		}
		"unix" {
			if {![catch {open "/proc/cpuinfo"} f]} {
				set cores [regexp -all -line {^processor\s} [read $f]]
				close $f
				if {$cores > 0} {
					return $cores
				} else {
					puts "Warning: failed to retrieve number of processors: parse error"
					return 1
				}
			} else {
				puts "Warning: failed to retrieve number of processors: cannot open /proc/cpuinfo"
				return 1
			}
		}
		default { 
			puts "Warning: failed to retrieve number of processors: unsupported platform"
			return 1
		}
	}
}

	set build_configuration FromSource
	::pct::set_default_encap_config SPICtrl/SPICtrl "FastBuild"
	::pct::remove_encap_config SYSTEM_LIBRARY:SPICtrl/SPICtrl "FromSource"
	if {[info exists ::env(TLMCREATOR_BUILD_CONFIGURATION)]} {
		set build_configuration $::env(TLMCREATOR_BUILD_CONFIGURATION)
	} else {
		set build_configuration "FastBuild"
	}



	::pct::generate_dynamic_load_adapter SYSTEM_LIBRARY:SPICtrl/SPICtrl "FastBuild" [file normalize [file dirname [info script]]]/../../SystemC/src/SPICtrl.dladapter.cc

	::pct::build_encap_config SYSTEM_LIBRARY:SPICtrl/SPICtrl $build_configuration -j[number_of_processors]

	foreach encap_config [::pct::list_encap_configs SPICtrl/SPICtrl] {
		::pct::package_encap_build_config SPICtrl/SPICtrl $encap_config
	} 
	
	
	::pct::export_system_library SPICtrl [file normalize [file dirname [info script]]]/SPICtrl.xml
	if {[file exists [file normalize [file dirname [info script]]]/SPICtrl_build_user_post.tcl]} { source [file normalize [file dirname [info script]]]/SPICtrl_build_user_post.tcl }
}

