/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 * Author:  Synopsy
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:979953aece613dc798a44b5badea4c71424e266d 

#pragma once

#include "SPICtrlMirrorBase.h"



class SPICtrlMirror : public SPICtrlMirrorBase {
  public:
    SC_HAS_PROCESS(SPICtrlMirror);

    SPICtrlMirror(sc_core::sc_module_name name) : SPICtrlMirrorBase(name) {
    }
};

