This directory contains the example code for Assignment 1 of the course
Electronic System Level Design Methodology, School Year 2025.

File list:
	DMA.h		// The module definition of DMA
	DMA.cpp	 	// The b_transport & process implementation of DMA
	CPU.h		// A fake CPU header as part of the testbench
	CPU.cpp		// A fake CPU process implementation
	MEM.h		// A memory header as part of the testbench
	MEM.cpp		// A memory b_transport and process implementation
	main.cpp	// The example test suite, i.e. sc_main
	Makefile	// The Make script for SystemC 3.0.2
	README		// This file
	Gemini		// A simple DMA generated by Gemini

Notes
Assuming that SystemC 3.0.2 is installed at /usr/local/systemc-3.0.2. Also
assume that -std=c++17 is supported. Therefore in the Makefile a
parameter SYSTMEC_DIR is set to SYSTEMC_HOME, i.e. /usr/local/systemc-3.0.2,
the compiler is g++ -std=c++17, the include flags INCFLAGS addresses to
${SYSTEMC_DIR}/include, and the link flags LDFLAGS addresses to
${SYSTEMC_DIR}/lib. Please be noted that the Dynamic-Link Library (DLL)
rpath setting, has to be presented as:

-Wl,rpath,${SYSTEMC_DIR}/lib

============================================================================
If the execution has following error message:

timer: error while loading shared libraries: libsystemc-3.0.2.so: cannot open shared object file: No such file or directory

it means the LD_LIBRARY_PATH does not contain the SystemC library. Correct
this problem by giving below shell command or add it into your .bashrc:

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/systemc-3.0.2/lib

============================================================================
If the execution has following error message:

dyld[23262]: Library not loaded: @rpath/libsystemc.3.0.dylib
Reason: no LC_RPATH's found

It means the rpath is not set correctly. Add below setting into the linking
command. It can be inserted into the LDFLAGS of the Makefile:

    -Wl,rpath,${SYSTEMC_DIR}/lib

============================================================================
If the execution has following error message:

/usr/bin/ld: cannot find -lsystemc

It is likely that during the SystemC installation in your environment,
it is not lib to be created in SYSTEMC_HOME. Maybe it is lib-linux64 or
lib-macos or something else. You can fix the problem by one of the following
two methods. Assume that it is lib-linux64 in your environment:

Method 1: change the Makefile, lib into lib-linux64
Method 2: in /usr/local/systemc-3.0.2, do

ln -s lib-linux64 lib

to create a soft link (ln -s) named lib that points to lib-linux64. Although
you only need to use one of the two methods above, it is not a problem that
you do both. Method 2 is more convenient since it allows the use of both
lib and lib-linux64.
 
===========================================================================
DMA.h and DMA.cpp

This DMA has more capabilities than required by the assignment description.
It has a flag to block from overwrite SOURCE, TARGET, and SIZE registers
during the data movement is in progress. However, change START to 0 during
data movement is allowed to suspend the data move. START can be changed back
to 1 to resume the data move. Or the user can write new SOURCE, TARGET,
and SIZE for a new data move when the START has changed to 1 again.

Not only WRITE operations are supported in the b_transport, the READ
operations are also supported. This is again another out-of-scope feature.

For above out-0f-scope features the CPU also tests these features by
writting to SOURCE during data move. Tests to clear START to suspend
the data move, then set START to resume the data move are also been conducted.

The DMA generated by Gemini fits the assignment description. However, there is
no wait(delay) in b_transport to simulate the transaction latency. And the
testbench (main.cpp) is poor and cannot show if the DMA is properly
implemented.

