/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 

/***************************************************************************
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:abfbae24c75cb404d9f3c557420592c9a622779f 

#include <ex_import_blockTestHarness.h>



using namespace scml2::testing;


template<typename Ttn = int, bool Tb = false, int Tint = 1>
class ex_import_blockTest : public ex_import_blockTestHarness<Ttn, Tb, Tint> {

  // Register the test class and all test methods
  SCML2_BEGIN_TESTS(ex_import_blockTest);
  SCML2_TEST(testAlwaysSucceeds);
  SCML2_END_TESTS();

  ex_import_blockTest() {
  }
  
  // Override this if you want a customize construction of your model under test // ! Only available when not reusing component build in test
  //virtual ex_import_block<Ttn, Tb, Tint>* create_model_under_test(const char* name) { // ! Only available when not reusing component build in test
  //  return new ex_import_block<Ttn, Tb, Tint>(name); // ! Only available when not reusing component build in test
  //}

  // Override this if you want to customize construction of your mirror model
  //virtual ex_import_blockMirrorBase<Ttn, Tb, Tint>* create_mirror_model(const char* name) {
  //  return new ex_import_blockMirrorBase<Ttn, Tb, Tint>(name);
  //}
    
  // initialize is called once at the start of the test run, after the model and
  // the mirror model have been created & connected. Initialize the models further here,
  // set up extra connections, set clock periods, ...
  virtual void initialize() {
  }
  
  // Called before running each testcase
  // Reset your model here.
  virtual void setup() {
  }
  
  // Called after running each testcase
  virtual void teardown() {
  }
  
  // Called at the end of the complete testrun
  virtual void shutdown() {
  }
  
  void testAlwaysSucceeds() {
    //enable_logging()
	SCML2_ASSERT_THAT(true, "test always succeeds");
 }  
};



namespace {
  typedef ex_import_blockTest<int, true, 0> ex_import_blockTest_int__true__0_;
  typedef ex_import_blockTest<int, false, 0> ex_import_blockTest_int__false__0_;
  typedef ex_import_blockTest<int, true, 1> ex_import_blockTest_int__true__1_;
}
//SCML2_REGISTER_TEST_GROUP_WITH_PARAMETERS(ex_import_blockTest_int__true__0_, parameter_configurations(parameter_configuration("Default")("ca_int", 0)("ca_bool", true)("ca_double", 0.0)("ca_string", "any")("p_uint", 2)("p_bool", true)("p_double", 3.14)("p_string", "one")));
SCML2_REGISTER_TEST_GROUP(ex_import_blockTest_int__true__0_);
//SCML2_REGISTER_TEST_GROUP_WITH_PARAMETERS(ex_import_blockTest_int__false__0_, parameter_configurations(parameter_configuration("Default")("ca_int", 0)("ca_bool", true)("ca_double", 0.0)("ca_string", "any")("p_uint", 2)("p_bool", true)("p_double", 3.14)("p_string", "one")));
SCML2_REGISTER_TEST_GROUP(ex_import_blockTest_int__false__0_);
//SCML2_REGISTER_TEST_GROUP_WITH_PARAMETERS(ex_import_blockTest_int__true__1_, parameter_configurations(parameter_configuration("Default")("ca_int", 0)("ca_bool", true)("ca_double", 0.0)("ca_string", "any")("p_uint", 2)("p_bool", true)("p_double", 3.14)("p_string", "one")));
SCML2_REGISTER_TEST_GROUP(ex_import_blockTest_int__true__1_);


