/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:ecc27bae5bb897d526a478eb7c68bdf6fc6e56f2 

#pragma once

#include <scml2_testing.h>
#include </home/user1/sc25/sc2568/TLMCreation_Quickstart_Training_X-2025.06/TLMC_Training_X-2025.06/labs/tlmcTrainingLabData/tlmcTrainingLabData/data/module_3/ImportSystemC/include/block.h>
#include <ex_import_blockMirror.h>
#include <ex_import_blockCovermodel.h>



#include <scml2_testing/fb_test_utils.h>



namespace {
  typedef ex_import_block<int, true, 0> ex_import_block_int__true__0_;
  typedef ex_import_block<int, false, 0> ex_import_block_int__false__0_;
  typedef ex_import_block<int, true, 1> ex_import_block_int__true__1_;
}


SCML2_FASTBUILD_COVERAGE(::ex_import_block_int__true__0_, "ex_import_block0<int, true, 0>", "ex_import_block" + std::string(::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") ? std::string(",")+::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") : "") + ",../../SystemC/libso-gcc-12.3-64/FastBuild,..;");
SCML2_FASTBUILD_COVERAGE(::ex_import_block_int__false__0_, "ex_import_block0<int, false, 0>", "ex_import_block" + std::string(::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") ? std::string(",")+::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") : "") + ",../../SystemC/libso-gcc-12.3-64/FastBuild,..;");
SCML2_FASTBUILD_COVERAGE(::ex_import_block_int__true__1_, "ex_import_block0<int, true, 1>", "ex_import_block" + std::string(::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") ? std::string(",")+::getenv("SNPS_VP_PRIMARY_DYNAMIC_LOAD_PATH") : "") + ",../../SystemC/libso-gcc-12.3-64/FastBuild,..;");


template<typename Ttn = int, bool Tb = false, int Tint = 1>
class ex_import_blockTestHarness : public scml2::testing::test_group<::ex_import_block<Ttn, Tb, Tint>, ex_import_blockMirror<Ttn, Tb, Tint>, scml2::testing::fast_build_covergroup<ex_import_blockCovermodel<Ttn, Tb, Tint> > > {
  protected:
    ex_import_blockTestHarness() 
        : scml2::testing::test_group<::ex_import_block<Ttn, Tb, Tint>, ex_import_blockMirror<Ttn, Tb, Tint>, scml2::testing::fast_build_covergroup<ex_import_blockCovermodel<Ttn, Tb, Tint> > >()
        , p_uint("p_uint", this->get_property_server())
        , p_bool("p_bool", this->get_property_server())
        , p_double("p_double", this->get_property_server())
        , p_string("p_string", this->get_property_server())
        , ca_int("ca_int", this->get_property_server())
        , ca_bool("ca_bool", this->get_property_server())
        , ca_double("ca_double", this->get_property_server())
        , ca_string("ca_string", this->get_property_server()) {
      ca_int = 0;
      ca_bool = true;
      ca_double = 0.0;
      ca_string = "any";

    }
    
    scml2::testing::property_proxy<unsigned int> p_uint;
    scml2::testing::property_proxy<bool> p_bool;
    scml2::testing::property_proxy<double> p_double;
    scml2::testing::property_proxy<std::string> p_string;
    scml2::testing::property_proxy<int> ca_int;
    scml2::testing::property_proxy<bool> ca_bool;
    scml2::testing::property_proxy<double> ca_double;
    scml2::testing::property_proxy<std::string> ca_string;
    sc_core::sc_signal< bool > in_signal;
    scml2::testing::input_pin_proxy< bool > in;
    scml2::testing::target_socket_proxy<32> socket;
    sc_core::sc_signal< bool > p_reset_signal;
    scml2::testing::input_pin_proxy< bool > p_reset;
    scml2::testing::input_clock_proxy p_clk;


#ifndef SCML2_DONT_USE_TEST_HARNESS_CONSTANTS
    
#endif

  protected: 
    virtual void do_initialize_test_group() {
      in.set_target(&this->mirrorModel->in);
      this->modelUnderTest->in(in_signal);
      this->mirrorModel->in(in_signal);
      socket.set_target(&this->mirrorModel->socket);
      this->mirrorModel->socket(this->modelUnderTest->socket);
      p_reset.set_target(&this->mirrorModel->p_reset);
      this->modelUnderTest->p_reset(p_reset_signal);
      this->mirrorModel->p_reset(p_reset_signal);
      p_clk.set_target(&this->mirrorModel->p_clk_driver);
      this->modelUnderTest->p_clk(this->mirrorModel->p_clk);
    }
    
    virtual void do_initialize_properties() {
      this->init_param(p_uint, 2);
      this->init_param(p_bool, true);
      this->init_param(p_double, 3.14);
      this->init_param(p_string, "one");
      ca_int.initialize(this->get_model_under_test_name(), this->get_mirror_model_name());
      ca_bool.initialize(this->get_model_under_test_name(), this->get_mirror_model_name());
      ca_double.initialize(this->get_model_under_test_name(), this->get_mirror_model_name());
      ca_string.initialize(this->get_model_under_test_name(), this->get_mirror_model_name());
    }

};


