/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 * Author:  Synopsys
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:8d6f1d13c6bda13812a7b7068c7cd2b0bd1762e4 

#pragma once

#include "SPICtrlMirrorBase.h"



class SPICtrlMirror : public SPICtrlMirrorBase {
  public:
    SC_HAS_PROCESS(SPICtrlMirror);

    SPICtrlMirror(sc_core::sc_module_name name) : SPICtrlMirrorBase(name) {
    }
};

