/***************************************************************************
 * Copyright 1996-2025 Synopsys, Inc.
 *
 * This Synopsys software and all associated documentation are proprietary
 * to Synopsys, Inc. and may only be used pursuant to the terms and
 * conditions of a written license agreement with Synopsys, Inc.
 * All other use, reproduction, modification, or distribution of the
 * Synopsys software or the associated documentation is strictly prohibited.
 ***************************************************************************/
 
/***************************************************************************
 *
 * Warning: This is an auto-generated file. All changes to this file will be overwritten.
 *
 * Author:  Synopsys
 * Version: 1.0
 * Generated by: TLM Creator
 ***************************************************************************/

// CHECKSUM:5cba6ae42f86e61041becaa330dd5872e8dbf63a 


#pragma once

#include <systemc>
#include <scmlinc/scml_property.h>
#include <scml2.h>
#include <scml2_base.h>
#include <scml2_protocol_engines/tlm2_ft_initiator_port/include/tlm2_ft_initiator_port_pe.h>
#include <tlm_ft_spi_mockup.h>
#include <scml2_protocol_engines/reset/include/reset_engine.h>
#include <scml2_protocol_engines/clock/include/clock_engine.h>
#include <scml2_protocol_engines/interrupt/include/interrupt_engine.h>




class SPICtrlMirrorBase : public sc_core::sc_module {
  public:
    SC_HAS_PROCESS(SPICtrlMirrorBase);

	typedef SPICtrlMirrorBase ModelBaseType;

    SPICtrlMirrorBase(sc_core::sc_module_name name) 
        : sc_core::sc_module(name)
        , enable_check_clocks("enable_check_clocks", false)
        , target_id("target_id", 0)
        , fifo_size("fifo_size", 5)
        , version("version", 10003)
        , bus_reg_in("bus_reg_in")
        , rst_in("rst_in")
        , spi_clk("spi_clk")
        , clk_in("clk_in")
        , tfuf_irq("tfuf_irq")
        , tfff_irq("tfff_irq")
        , rfof_irq("rfof_irq")
        , rfdf_irq("rfdf_irq")
        , bus_reg_in_mockup("bus_reg_in_mockup", bus_reg_in)
        , Serial_IO_mockup("Serial_IO_mockup")
        , rst_in_mockup("rst_in_mockup", rst_in)
        , spi_clk_mockup("spi_clk_mockup", spi_clk)
        , clk_in_mockup("clk_in_mockup", clk_in)
        , tfuf_irq_mockup("tfuf_irq_mockup", tfuf_irq)
        , tfff_irq_mockup("tfff_irq_mockup", tfff_irq)
        , rfof_irq_mockup("rfof_irq_mockup", rfof_irq)
        , rfdf_irq_mockup("rfdf_irq_mockup", rfdf_irq) {
      bus_reg_in_mockup.abstraction = scml2::LT;
      /* bus_reg_in_mockup.dmi_enabled = ; */
      bus_reg_in_mockup.consume_annotated_time = false;
      bus_reg_in_mockup.finalize_construction();
      Serial_IO_mockup.version = V3_0;
      Serial_IO_mockup.finalize_construction();
      rst_in_mockup.mode = scml2::DURATION;
      rst_in_mockup.active_level = false;
      /* rst_in_mockup.duration = ; */
      rst_in_mockup.enable_debug_trigger = false;
      rst_in_mockup.finalize_construction();
      spi_clk_mockup.m_mode = scml2::clock_mode::ACTIVE;
      spi_clk_mockup.m_period = sc_core::sc_time(10, SC_NS);
      spi_clk_mockup.m_enabled = true;
      spi_clk_mockup.finalize_construction();
      clk_in_mockup.m_mode = scml2::clock_mode::ACTIVE;
      clk_in_mockup.m_period = sc_core::sc_time(10, SC_NS);
      clk_in_mockup.m_enabled = true;
      clk_in_mockup.finalize_construction();
      tfuf_irq_mockup.active_level = false;
      tfuf_irq_mockup.finalize_construction();
      tfff_irq_mockup.active_level = false;
      tfff_irq_mockup.finalize_construction();
      rfof_irq_mockup.active_level = false;
      rfof_irq_mockup.finalize_construction();
      rfdf_irq_mockup.active_level = false;
      rfdf_irq_mockup.finalize_construction();
    }
    
    ~SPICtrlMirrorBase() {
      m_actions.clear();
    }
    
    /**
     * This method resets all interfaces, registers, and bitfields to their reset value.
     * It is typically called from end_of_elaboration(), and connected to the reset port.
     */
    
    virtual void reset_model() {
    }
    
    virtual void end_of_elaboration() {
      sc_core::sc_module::end_of_elaboration();
      reset_model();
    }
    
    ModelBaseType& model() {
      return *this;
    }
     
    
    
    /* Enable/disable the check on the SPI clock communication */
    scml_property<bool> enable_check_clocks;
    /* Identify SPI when in input mode */
    scml_property<unsigned int> target_id;
    /* Size of the internal FIFOs */
    scml_property<unsigned int> fifo_size;
    scml_property<int> version;
    
    scml2::ft_initiator_socket<32> bus_reg_in;
    sc_core::sc_out<bool> rst_in;
    sc_core::sc_export<sc_core::sc_signal_inout_if<bool> > spi_clk;
    sc_core::sc_export<sc_core::sc_signal_inout_if<bool> > clk_in;
    sc_core::sc_in<bool> tfuf_irq;
    sc_core::sc_in<bool> tfff_irq;
    sc_core::sc_in<bool> rfof_irq;
    sc_core::sc_in<bool> rfdf_irq;
    
    
    
    scml2::base::actions m_actions;
    scml2::tlm2_ft_initiator_port_pe<32> bus_reg_in_mockup;
    scml2::testing::tlm_ft_spi_mockup Serial_IO_mockup;
    scml2::reset_master_engine rst_in_mockup;
    scml2::clock_master_engine spi_clk_mockup;
    scml2::clock_master_engine clk_in_mockup;
    scml2::interrupt_slave_engine tfuf_irq_mockup;
    scml2::interrupt_slave_engine tfff_irq_mockup;
    scml2::interrupt_slave_engine rfof_irq_mockup;
    scml2::interrupt_slave_engine rfdf_irq_mockup;
};

